### ISSUE TITLE
fix: outputs invalid glyph

### ISSUE THREAD

**Issue by garytryan** [itgalaxy/webfont#137]
```
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="22" viewBox="0 0 24 22">
    <g fill="none" fill-rule="evenodd">
        <path fill="#4223B9" d="M22.222 7.333V6.205v1.128H0V2.256C0 1.012 1.022 0 2.28 0h6.837c.133 0 .262.046.364.13l3.26 2.69h7.202c1.257 0 2.28 1.013 2.28 2.257v2.256z"/>
        <rect width="24" height="16.72" y="5.28" fill="#6849FC" rx="1.778"/>
    </g>
</svg>
```

outputs the following glyph
```
<glyph
      glyph-name="folder"
      unicode="&#xEA02;"
      horiz-adv-x="24"
      d="M22.222 14.667V15.795V14.667H0V19.744C0 20.988 1.022 22 2.28 22H9.117C9.25 22 9.379 21.954 9.481 21.87L12.741 19.18H19.943C21.2 19.18 22.223 18.167 22.223 16.923V14.667zM1.778 16.72H22.222ANaN NaN NaN 0 0 24 16.72V0ANaN NaN NaN 0 0 22.222 0H1.778ANaN NaN NaN 0 0 0 0V16.72ANaN NaN NaN 0 0 1.778 16.72z"
/>
```

I notice there's some NaNs in there.

**Comment by evilebottnawi** [comment]
@garytryan can you put here svg icon with name `folder`?

**Comment by garytryan** [comment]
@evilebottnawi 

Yeah, this is the `folder` svg

```
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="22" viewBox="0 0 24 22">
    <g fill="none" fill-rule="evenodd">
        <path fill="#4223B9" d="M22.222 7.333V6.205v1.128H0V2.256C0 1.012 1.022 0 2.28 0h6.837c.133 0 .262.046.364.13l3.26 2.69h7.202c1.257 0 2.28 1.013 2.28 2.257v2.256z"/>
        <rect width="24" height="16.72" y="5.28" fill="#6849FC" rx="1.778"/>
    </g>
</svg>
```

**Comment by jimmyandrade** [comment]
> @garytryan Thanks i will investigate in near future 👍

@evilebottnawi did we have any news about this investigation?

> I notice there's some NaNs in there.

@garytryan did you continue to have these problems? If so, please tell us and we will help you. Otherwise, I would like to close this issue. Thanks

**Comment by garytryan** [comment]
> > @garytryan Thanks i will investigate in near future 👍
> 
> @evilebottnawi did we have any news about this investigation?
> 
> > I notice there's some NaNs in there.
> 
> @garytryan did you continue to have these problems? If so, please tell us and we will help you. Otherwise, I would like to close this issue. Thanks

@jimmyandrade I'm not using this anymore. Please feel free to close. Thanks!

**Comment by jimmyandrade** [comment]
@garytryan no prob, thank you.
