### ISSUE TITLE
feat: ligatures

### ISSUE THREAD

**Issue by efc-ls** [itgalaxy/webfont#174]
Hey,

is it possible to set custom ligatures?
So that my html can look like this:
`<span class="fontclass">iconname</span>`

**Comment by evilebottnawi** [comment]
ligatures? Do you mean class?

**Comment by lswug** [comment]
If my css looks like this:
```
@font-face {
    font-family: TestFont;
    ...
}

.test_font {
    font: normal normal 400 14px/1 TestFont;
    ...
}

.test_font-house::before {
    content: "\ea01";
}
```

So I can use my html tag just like this:
`<span class="test_font test_font-house"> This is a text</span>`

> -> **HouseIcon** This is a text

also this:
`<span class="test_font">&#xEA01; This is a text</span>`

> -> **HouseIcon** This is a text

But I want to achive this:
`<span class="test_font">font-house This is a text</span>`

> ->**HouseIcon** This is a text

As I researched correctly this is solved with creating ligatures. Those are added in the "gsub"(?) part of the *.tff and *.woff

**Comment by evilebottnawi** [comment]
I think you can use custom css template for this case and generate own css

**Comment by lswug** [comment]
Well, IMHO it's not done with just creating css. The text has to be rendered into the icon..
Anyways I'll find a workaround, I was wondering if there are any possibilities.
Thanks :-)

**Comment by evilebottnawi** [comment]
@lswug You can send a PR :+1:

**Comment by mpalpha** [comment]
Check out [Ligatures](https://google.github.io/material-design-icons/#using-the-icons-in-html) for more information.

**Comment by jimmyandrade** [comment]
@guluws thanks for suggesting this feature.

@mpalpha added the PR https://github.com/itgalaxy/webfont/pull/191 and we've just merged.
We will plan a release soon, and you find issues related to glyphs and ligatures, please feel free to share 😄

**Comment by lehni** [comment]
@jimmyandrade this has been released since, correct? In that case, the issue can be closed?

**Comment by jimmyandrade** [comment]
> @jimmyandrade this has long been released since, correct? In that case, the issue can be closed?

@lehni yes, it can be closed. Thanks for helping me to remind it!
