### ISSUE TITLE
Export glyph data in result

### ISSUE THREAD

**Issue by misterbrownlee** [itgalaxy/webfont#18]
It would be handy (at least for my useage) to have access to the raw glyph data, especially the metadata and the unicode mappings.  It would be pretty easy to add this as an optional setting.  I will PR unless I'm missing a way to access that already?  Other systems I've encountered allow this through a 'glyph' emitter.  I also thought I might hack the mapping data out with a custom css template but I would rather not go there :)

LMK if you're against this or if I'm missing something?  Thanks!

**Comment by evilebottnawi** [comment]
@misterbrownlee let's do it, wait PR :smile:

**Comment by misterbrownlee** [comment]
I realized that `glyphTransformFn` exposes the glyph metadata to a function. It would also be easy to use that to write the data back into the result hash, or save it to a separate file, etc.  Maybe that's better than another option, I'll write a gist for that and we can talk when that's done.

**Comment by evilebottnawi** [comment]
Done in `8.0.0` in `glyphsData` export object. i will release new version today :+1:
