### ISSUE TITLE
Array values in config file are being merged into the defaults

### ISSUE THREAD

**Issue by lepus2589** [itgalaxy/webfont#184]
If you use a config file and try to set the formats option to something other than the default, webfont will still generate the default set of font formats. 

The following line seems the culprit:

https://github.com/itgalaxy/webfont/blob/6bacf7697a6d5acd6df038ce0fb6c20fe9fcb2fc/src/standalone.js#L218

`deepmerge()` concats the formats array from the config file with the default array instead of replacing it, which results in the following: `formats: ['svg', 'ttf', 'eot', 'woff', 'woff2', 'svg', 'ttf', 'eot']`

**Comment by evilebottnawi** [comment]
oh, it is bug, PR welcome

**Comment by evilebottnawi** [comment]
Should be use to fix

**Comment by iantearle** [comment]
This is still an issue with the CLI - passing --format with any value results in all fonts in the default being compiled
