### ISSUE TITLE
Upgrading from 8.2.1 to 9.0.0 breaks typescript builds

### ISSUE THREAD

**Issue by TabithaLarkin** [itgalaxy/webfont#187]
As part of [this commit](https://github.com/itgalaxy/webfont/commit/f2b82d6659ad7b0da5790f6642dcb6b377d6fb98) to update dependencies, the version of globby was updated to 9.0.0 from 8.0.1. This has introduced a dependency on `@types/glob` which introduces a dependency on `@types/node`.

Upgrading to the new version of webfont breaks our typescript build, as it now imports the `@types/node` package automatically due to the way typescript's type detection works.

I have also raised this as an issue in the [globby repo](https://github.com/sindresorhus/globby/issues/129).

**Comment by evilebottnawi** [comment]
Looks problem not on our side
