### ISSUE TITLE
chore: search contributors 

### ISSUE THREAD

**Issue by alexander-akait** [itgalaxy/webfont#190]
Unfortunately i don't have enough time on this package so i need help.

Write something here if you want to help.

**Comment by jimmyandrade** [comment]
@evilebottnawi I can help :) We use `webfont` on @naturacosmeticos.

**Comment by evilebottnawi** [comment]
@jimmyandrade Thanks, I can invite you, what do you want to start fixing?

**Comment by jimmyandrade** [comment]
@evilebottnawi I would start by taking a look at the dependency update PRs that currently exist, and possible security fixes. What do you think?

**Comment by evilebottnawi** [comment]
Sent invalie

**Comment by jimmyandrade** [comment]
Thank you.

By the way, what is the path-to-production for launching new versions? I saw that the repository uses `standard-version`. Version bump is done in the pipeline, do you publish in your local development environment?

**Comment by evilebottnawi** [comment]
Yes, I do it locally, no automation

**Comment by jimmyandrade** [comment]
@evilebottnawi another question: I noticed that there are some `greenkeeper/*` branches.
Greenkeeper’s operation was stopped as an independent service on June 3rd, 2020.

I could remove these old branches from the greenkeeper, and thus focus on merging some Snyk PRs.
What do you think?

**Comment by evilebottnawi** [comment]
Yes, feel free to remove `greenkeeper` in favor `depedabot` and close old branches
