### ISSUE TITLE
Latest release uses vulnerable yargs-parser

### ISSUE THREAD

**Issue by chrisdjali-wrld3d** [itgalaxy/webfont#302]
The 9.0.0 release depends on `yargs-parser` `^10.0.0` via `meow` `^5.0.0`. It looks like this has been resolved on the master branch, but no release has happened since then. This means that users of the NPM package will fail `npm audit`.

**Comment by iainbethune** [comment]
Yep, seems this was resolved here: https://github.com/itgalaxy/webfont/pull/195

Any chance of a new release with the fix @jimmyandrade 🙏

**Comment by jimmyandrade** [comment]
@chrisdjali-wrld3d thanks for sharing and reminding us of this issue.

@iainbethune thanks for asking. I still can't release a new version by myself, because I don't have NPM publishing tokens yet, I need help from @evilebottnawi. 

@evilebottnawi could you help us with this?

**Comment by iainbethune** [comment]
Just wondering if there is any update on getting a new release out @jimmyandrade @alexander-akait?

**Comment by jimmyandrade** [comment]
@iainbethune I still can't release a new version by myself.

@alexander-akait could you give me permissions for publishing `webfont` on npm?

**Comment by alexander-akait** [comment]
@jimmyandrade can you give me your npm account?

**Comment by alexander-akait** [comment]
Sorry for delay, there are a lot of issues (over 200-300 every day)

**Comment by jimmyandrade** [comment]
> @jimmyandrade can you give me your npm account?

Of course! It's `jimmyandrade` (https://www.npmjs.com/~jimmyandrade)

> Sorry for delay, there are a lot of issues (over 200-300 every day)

Wow! I had no idea. I hope that with these publishing permissions I will help you to decrease at least some of these requests 😊

**Comment by jimmyandrade** [comment]
> @jimmyandrade can you give me your npm account?

@alexander-akait  Of course! It's `jimmyandrade` (https://www.npmjs.com/~jimmyandrade)

> Sorry for delay, there are a lot of issues (over 200-300 every day)

Wow! I had no idea. I hope that with these publishing permissions I will help you to decrease at least some of these requests 😊

**Comment by alexander-akait** [comment]
I really hate `npm`, they just removed the ability to add outside collaborators, every time when I am working with npm something goes wrong, @jimmyandrade sent invite

**Comment by alexander-akait** [comment]
@jimmyandrade now you can publish https://www.npmjs.com/package/webfont, don't forget to enable 2FA to security

**Comment by iainbethune** [comment]
Just got an automated about this from github today... are we any closer to getting a new release out @jimmyandrade?

P.S.  Thanks for both of you guys spending your time solving this :)

**Comment by goozo** [comment]
just wondering if the new release is going to be published soon addressing this issue? cheers.

**Comment by jimmyandrade** [comment]
> just wondering if the new release is going to be published soon addressing this issue? cheers.

I have great news! Now I can publish packages, so Webfont 10 was released yesterday with many dependency upgrades. (It's a breaking change because we removed support to legacy Node versions).

Could you please try v10.0.0? Thanks!

**Comment by chrisdjali-wrld3d** [comment]
Looks like this has been resolved now, so I'm closing it.
