### ISSUE TITLE
generate data:application/x-font-woff;charset=utf-8;base64,... URL style in templates

### ISSUE THREAD

**Issue by IgnacioHR** [itgalaxy/webfont#328]
Hi,

This is a feature request!

I would like to generate an SCSS template with embedded font URLs rather than a URL pointing to an external file. This is to speedup the font loading (at the cost of increasing the file size) without having to open an additional http request to the web server.

To be more concise. Current templates are based on nunjuncs and inside the template we have access to options. But AFAIK there is no access to the result.ttf, result.woff, result.woff2 fields that are part of result {}. So it is not possible to use the Buffer.toString('base64') method and generate an URL of the form url="data:font/woff2;base64,...." inside the @webfont

I'll try to clone the repository and implement this change for my own purposes and, if there is interest, I'll be happy to share my changes.

Cheers
Ignacio

**Comment by jimmyandrade** [comment]
@IgnacioHR thanks for contributing!

Your feature request was accepted and released as [Webfont 11.1](https://github.com/itgalaxy/webfont/releases/tag/v11.1.0) and already available at [npm](https://www.npmjs.com/package/webfont/v/11.1.0).
