### ISSUE TITLE
Incomplete after compilation

### ISSUE THREAD

**Issue by XiongC-sss** [itgalaxy/webfont#453]
**Hello, I encountered a bug in version 11.2.4. Although I used svgo to optimize the svg, it was incomplete after compilation**
`<svg class="icon" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg" width="128" height="128">
    <path d="M512 1013.333c-276.885 0-501.333-224.448-501.333-501.333S235.115 10.667 512 10.667 1013.333 235.115 1013.333 512 788.885 1013.333 512 1013.333zm0-64c241.536 0 437.333-195.797 437.333-437.333S753.536 74.667 512 74.667 74.667 270.464 74.667 512 270.464 949.333 512 949.333z"
          fill="#cdcdcd"/>
    <path d="M488.235 482.432v-166.55a32 32 0 0 1 64 0v166.55h166.549a32 32 0 0 1 0 64h-166.55v166.55a32 32 0 1 1-64 0v-166.55H321.686a32 32 0 1 1 0-64h166.55z"
          fill="#cdcdcd"/>
</svg>`

**Comment by XiongC-sss** [comment]
<svg class="icon" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg" width="128" height="128">
    <path d="M512 1013.333c-276.885 0-501.333-224.448-501.333-501.333S235.115 10.667 512 10.667 1013.333 235.115 1013.333 512 788.885 1013.333 512 1013.333zm0-64c241.536 0 437.333-195.797 437.333-437.333S753.536 74.667 512 74.667 74.667 270.464 74.667 512 270.464 949.333 512 949.333z"
          fill="#cdcdcd"/>
    <path d="M488.235 482.432v-166.55a32 32 0 0 1 64 0v166.55h166.549a32 32 0 0 1 0 64h-166.55v166.55a32 32 0 1 1-64 0v-166.55H321.686a32 32 0 1 1 0-64h166.55z"
          fill="#cdcdcd"/>
</svg>

**Comment by jimmyandrade** [comment]
@XiongC-sss did the problem keep happening?
