### ISSUE TITLE
Globby now uses ESM

### ISSUE THREAD

**Issue by lucavb** [itgalaxy/webfont#464]
Hey,

in your package.json you specified to use the [latest version](https://github.com/itgalaxy/webfont/blob/master/package.json#L44) of `globby`. However, they recently updated to version 12, which is a major update, and have turned [their package into a pure ESM](https://github.com/sindresorhus/globby/releases/tag/v12.0.0) module and now the tests for webfont fail do as well as our usage. The import needs to be updated in webfont. Maybe I have time for this this evening. Also why did you opt for using `latest` for dependencies? That feels a bit risky to me and leaves you open to events such as this.

**Comment by Schascha** [comment]
A downgrade to 9.0.0 will help for now.

**Comment by lucavb** [comment]
Yes and no. Version 9 was not written in TypeScript and does not have a `@types/` package.

**Comment by wszydlak** [comment]
I agree that this package should not use `latest` versions. It is very risky.

**Comment by wszydlak** [comment]
I've prepared pull to use correct dependencies versions in #465 

This should be released as patch.

`webfont` still needs to bump `globby` and `meow`

**Comment by jimmyandrade** [comment]
@wszydlak thank you so much.

[v11.2.17](https://github.com/itgalaxy/webfont/releases/tag/v11.2.17) is now available at [npm](https://www.npmjs.com/package/webfont)
