### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by mk4arts** [itgalaxy/webfont#470]
Hi,

i wanted to try out your webfont compiler, but i'm having trouble to get this running...

Everytime i wanna run it, i get
```
/Users/xxx/dev/font/node_modules/webfont/dist/index.js:1
import require$$1, { createReadStream } from 'fs';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1025:15)
    at Module._compile (node:internal/modules/cjs/loader:1059:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/xxx/dev/font/generate.js:1:17)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
```

Repro:

package.json
```
{
  "name": "mdi",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "generate": "node generate.js"
  },
  "dependencies": {
    "webfont": "^11.2.17"
  }
}

```

generate.js
```
const webfont = require("webfont").default;

webfont({
  files: "src/svg-icons/**/*.svg",
  fontName: "my-font-name",
})
  .then((result) => {
    // Do something with result
    Function.prototype(result);
    // Or return it
    return result;
  })
  .catch((error) => {
    throw error;
  });
```

I also tried it with the import statement of your docs. As you can see the repro case is pretty simple and should work? What did i do wrong? I also tried to run it through babel, set `{type: "module"}` and all the other stuff you find on google.

**Comment by ppasler** [comment]
Same here :)

**Comment by db-it** [comment]
Same here :(

**Comment by wszydlak** [comment]
@jimmyandrade it happend after yesterday updates. There were no changes that could change code compilation to esm, haven't you changed it right before publishing?

**Comment by jimmyandrade** [comment]
>     "webfont": "^11.2.17"
Hi, @mk4arts. Thank you for reporting this. You did nothing wrong, it was my bad... I've published a wrong package version.

@mk4arts @ppasler @db-it 
Please upgrade to `webfont` 11.2.20, where this was fixed.
`11.2.17` version now is deprecated, installing it will ask to upgrade to version 11.2.20.

@wszydlak thank you for helping me with this :)

By the way, I'm trying to make semantic versioning more consistent.
This is not entirely up to me, as I don't have full control over publishing versions via CI.

**Comment by wszydlak** [comment]
@jimmyandrade  `webfont@11.2.20` works fine ! :)

**Comment by wszydlak** [comment]
@jimmyandrade looks like this issue could be closed

**Comment by jimmyandrade** [comment]
Thank you @wszydlak
