### ISSUE TITLE
Allow usage specify unicode code for each character

### ISSUE THREAD

**Issue by edouard-lopez** [itgalaxy/webfont#53]
I'm building a font from SVG files. For instance:

```
中.svg
山.svg
火.svg
西.svg
…
```
However 中 is associate with U+EA02 <Private Use> instead of U+4E2D CJK UNIFIED IDEOGRAPH-4E2D.

### Question

Is there a convention I'm missing to assign a glyph to the correct codepoint? 

**related:** parlr/Hanzi-Pinyin-Font#22 -  Associate glyph with correct codepoint.

**Comment by evilebottnawi** [comment]
@edouard-lopez thanks for feedback, i don't know why it is happens, need investigation, if you have time feel free to PR or create issue to related project :+1:

**Comment by edouard-lopez** [comment]
@evilebottnawi I used neither `startunicode` nor `prependUnicode` argument and name the SVG file with the character (not it's codepoint).

**Comment by evilebottnawi** [comment]
@edouard-lopez can you upload here one of svg?

**Comment by evilebottnawi** [comment]
@edouard-lopez oh sorry, I did not immediately understand what you specifically mean :smile: Filename of svg files not associated with real unicode characters (). Starting unicode https://github.com/nfroidure/svgicons2svgfont/blob/master/src/metadata.js#L17 Why you need associated real filename and unicode?

**Comment by edouard-lopez** [comment]
I generate the file from Unicode database, should I use the codepoint (e.g. `U+3400`)?

**Comment by evilebottnawi** [comment]
@edouard-lopez we can generate custom font and use the offset to not intersect with the real characters of the fonts. This approach is used by all font generators, if you can explain in more detail why you need it and for what, then maybe I can help

**Comment by edouard-lopez** [comment]
@evilebottnawi my goal is to generate a Chinese font based on Noto CJK (Chinese/Japenese/Korean) to add the pronunciation on top of each Chinese character, [see repo](https://github.com/parlr/Hanzi-Pinyin-Font), like example below.

![annotation-top](https://cloud.githubusercontent.com/assets/1212392/24404175/89cb361c-13c0-11e7-82d8-19f60d46afb7.png)

But the generated glyph should have the same codepoint as the original one otherwise it will be pointless as users won't be able to type the character.

**Comment by evilebottnawi** [comment]
@edouard-lopez Thanks for the explanation, I think it's workable, I'll try to find a solution this week, but you can try it yourself and send PR :+1:

**Comment by edouard-lopez** [comment]
I would expect an option `--detect-codepoint` based on the filename: either `U+3400.svg` or `㐀.svg`.                                                                                                                                                                                                    

What do you think?

**Comment by evilebottnawi** [comment]
@edouard-lopez sgtm for me!

**Comment by edouard-lopez** [comment]
@evilebottnawi  `svgicons2svgfont` already support what I wanted through a naming convengtion: 

    ${unicode}-${char.glyph}.svg

For example:

```
└── svg
    ├── u3400-㐀.svg
    ├── u3401-㐁.svg
    ├── u3404-㐄.svg
    ├── u3405-㐅.svg
    ├── u3406-㐆.svg
```

**Comment by evilebottnawi** [comment]
@edouard-lopez it is good :smile:
