### ISSUE TITLE
How can I use a configuration file?

### ISSUE THREAD

**Issue by yamaha252** [itgalaxy/webfont#64]
Hello! Thanks for the awesome package!
I had a problem to use a configuration file for run that package via cli.
I tried a lot of ways: in package.json, in .webfontrc etc.
I tried to run webfont and got different errors, for example:
```
webfont --config
/Users/yamaha/.nvm/versions/node/v6.10.2/lib/node_modules/webfont/node_modules/resolve-from/index.js:7
                throw new TypeError('Expected `fromDir` and `moduleId` to be a string');
```
```
webfont --config ".webfontrc"

  Generator of fonts from svg icons, svg icons to svg font, svg font to ttf, ttf to eot, ttf to woff, ttf to woff2

  Usage
      $ webfont [input] [options]

```
```
webfont ./src/assets/images/icons/*.svg -d ./src/assets/icons --config ./webfont.json
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at /Users/yamaha/.nvm/versions/node/v6.10.2/lib/node_modules/webfont/dist/standalone.js:161:55
```
```
webfont ./src/assets/images/icons/*.svg -d ./src/assets/icons --config"./webfont.json"
/Users/yamaha/.nvm/versions/node/v6.10.2/lib/node_modules/webfont/node_modules/resolve-from/index.js:7
                throw new TypeError('Expected `fromDir` and `moduleId` to be a string');
```
If I use without --config param my configs (in package.json and .webfontrc) aren't applied.

**Comment by evilebottnawi** [comment]
@yamaha252 thanks for feedback!
try `webfont "src/assets/images/icons/*.svg" --config ".webfontrc" -d "src/assets/icons"`

**Comment by yamaha252** [comment]
Thanks! But, I had an error again
```
webfont "src/assets/images/icons/*.svg" --config ".webfontrc" -d "src/assets/icons"
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at /Users/yamaha/.nvm/versions/node/v6.10.2/lib/node_modules/webfont/dist/standalone.js:161:55
```

**Comment by evilebottnawi** [comment]
@yamaha252 very strange `webpack` can't find template, can you create minimal repo with reproduce this?

**Comment by yamaha252** [comment]
Done: https://github.com/yamaha252/webfont-config

**Comment by evilebottnawi** [comment]
@yamaha252 thanks in near time i investigate this :+1:

**Comment by evilebottnawi** [comment]
@yamaha252 found bug thanks! Start to doing patch!

**Comment by evilebottnawi** [comment]
@yamaha252 try to new version https://github.com/itgalaxy/webfont/releases/tag/7.1.2

**Comment by yamaha252** [comment]
I updated the package to 7.1.2 in my minimal repo and got the same error:
```
webfont 'src/*.svg' --config '.webfontrc' -d 'dest/'
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at /Users/yamaha/.nvm/versions/node/v6.10.2/lib/node_modules/webfont/dist/standalone.js:161:55
```

**Comment by yamaha252** [comment]
I think the problem was not with 'template' param in a config. It seems can't process --config cli param correctly

**Comment by evilebottnawi** [comment]
@yamaha252 thanks try to investagate

**Comment by evilebottnawi** [comment]
@yamaha252 very strange i now try to use your example command and all work as expected, do you provide more information, maybe your don't update `webfont` (try `npm install webfont`)?

**Comment by yamaha252** [comment]
Oh, @evilebottnawi, I'm sorry. You're right. I've forgotten to update my global webfont package :)

**Comment by evilebottnawi** [comment]
@yamaha252 should search, investigate :+1:

**Comment by evilebottnawi** [comment]
@yamaha252 try https://github.com/itgalaxy/webfont/releases/tag/7.1.3

**Comment by yamaha252** [comment]
Great! It works perfectly now! Thanks a lot!
