### ISSUE TITLE
fix: SVG optimization messes up icons

### ISSUE THREAD

**Issue by japalo** [itgalaxy/webfont#80]
When adding complex icons some SVG optimization messes up the icons.

I can't find any related issues or similar threads, but if anyone knows a fix/workaround please tell me or point me in the right direction. :)

Example where icon fails:
`
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50.11 41.53"><defs><style>.cls-1{fill:#404040;}</style></defs><title>department</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><path class="cls-1" d="M24,12.51H9.31a1.94,1.94,0,0,0-1.94,1.93v1.1H4.21A4.21,4.21,0,0,0,0,19.75v2A4.21,4.21,0,0,0,4.21,26h7.3a4.21,4.21,0,0,0,4.21-4.21v-2a4.21,4.21,0,0,0-4.21-4.21H8.34v-1.1a1,1,0,0,1,1-1H24.58v2.07H21.41a4.21,4.21,0,0,0-4.21,4.21v2A4.21,4.21,0,0,0,21.41,26h3.17v2.07H17.91A1.94,1.94,0,0,0,16,30v1.1H12.81A4.21,4.21,0,0,0,8.6,35.3v2a4.21,4.21,0,0,0,4.21,4.21h7.3a4.21,4.21,0,0,0,4.21-4.21v-2a4.21,4.21,0,0,0-4.21-4.21H16.94V30a1,1,0,0,1,1-1H32.2a1,1,0,0,1,1,1v1.1H30A4.21,4.21,0,0,0,25.8,35.3v2A4.21,4.21,0,0,0,30,41.53h7.3a4.21,4.21,0,0,0,4.21-4.21v-2a4.21,4.21,0,0,0-4.21-4.21H34.14V30a1.94,1.94,0,0,0-1.94-1.93H25.54V26h3.17a4.21,4.21,0,0,0,4.21-4.21v-2a4.21,4.21,0,0,0-4.21-4.21H25.54V13.47H40.8a1,1,0,0,1,1,1v1.1H38.61a4.21,4.21,0,0,0-4.21,4.21v2A4.21,4.21,0,0,0,38.61,26h7.3a4.21,4.21,0,0,0,4.21-4.21v-2a4.21,4.21,0,0,0-4.21-4.21H42.74v-1.1a1.94,1.94,0,0,0-1.93-1.93H25.54V10.44h3.17a4.21,4.21,0,0,0,4.21-4.21v-2A4.21,4.21,0,0,0,28.71,0h-7.3A4.21,4.21,0,0,0,17.2,4.21v2a4.21,4.21,0,0,0,4.21,4.21h3.17v2.07ZM19.12,6.23v-2a2.28,2.28,0,0,1,2.28-2.28h7.3A2.28,2.28,0,0,1,31,4.21v2a2.28,2.28,0,0,1-2.28,2.28h-7.3A2.28,2.28,0,0,1,19.12,6.23ZM11.51,17.47a2.28,2.28,0,0,1,2.28,2.28v2a2.28,2.28,0,0,1-2.28,2.28H4.21a2.28,2.28,0,0,1-2.28-2.28v-2a2.28,2.28,0,0,1,2.28-2.28h7.3ZM22.39,35.3v2a2.28,2.28,0,0,1-2.28,2.28h-7.3a2.28,2.28,0,0,1-2.28-2.28v-2A2.28,2.28,0,0,1,12.81,33h7.3A2.28,2.28,0,0,1,22.39,35.3Zm17.2,0v2a2.28,2.28,0,0,1-2.28,2.28H30a2.28,2.28,0,0,1-2.28-2.28v-2A2.28,2.28,0,0,1,30,33h7.3A2.28,2.28,0,0,1,39.59,35.3ZM28.71,17.47A2.28,2.28,0,0,1,31,19.75v2a2.28,2.28,0,0,1-2.28,2.28h-7.3a2.28,2.28,0,0,1-2.28-2.28v-2a2.28,2.28,0,0,1,2.28-2.28h7.3Zm19.48,4.31a2.28,2.28,0,0,1-2.28,2.28h-7.3a2.28,2.28,0,0,1-2.28-2.28v-2a2.28,2.28,0,0,1,2.28-2.28h7.3a2.28,2.28,0,0,1,2.28,2.28Z"/></g></g></svg>
`

Using this npm script:
`"webfont-gen": "webfont ./src/icons/*.svg --dest ./pat-to-dest -f icon --center-horizontally --fixed-width --template ./path-to-template --dest-styles ./path-to-dest/ --css-template-font-path /path-to-css-template/"`

EDIT: I forgot to tell you what i actually expect. I would either like a fix for my problems, or a way to "turn off" the optimization in my npm script.

**Comment by evilebottnawi** [comment]
@japalo can your provide what your expected and what is actually happens?

**Comment by japalo** [comment]
I expected this (screenshot from OSx preview:
![skarmavbild 2017-05-22 kl 15 17 46](https://cloud.githubusercontent.com/assets/5397459/26310673/fd69df76-3f01-11e7-964a-fd786f60321b.png)

And i got this (screenshot from webpage where icon font has rendered font from SVG):
![skarmavbild 2017-05-22 kl 15 18 49](https://cloud.githubusercontent.com/assets/5397459/26310674/fd6df494-3f01-11e7-9aa5-92d3caff4621.png)

**Comment by japalo** [comment]
When i tried to boost up the size of the icons to 512px * 512px instead of 56px * 56px the lines smoothed out a bit, but the fill was weird instead. Will try to edit SVGs in order to update you.

**Comment by evilebottnawi** [comment]
@japalo do your use `svgo` or some similar tools?

**Comment by japalo** [comment]
Worked with the designer and we found out after multiple SVG export form illustrator and sketch that:
1. Sketch export did not work at all for this. Something with the fill-mode i suppose. Either the fills where behaving unexpectedly or the fills where inverted.
2. Illustrator needs to export a large SVG. We used 512px*512px
3. All shapes needs to be finalized and using "Compound path".

I think this was/is issues that touches both the SVG export and the rendering of fonts. The SVG export from illustrator seems to have issues when exporting small sized complex shapes. This in turn made the generator confused while optimizing the icon.

The safe way of working with this seems to be to go large. I am not sure why, since SVGs are using bezier curves, but this is probably nice to mention in the readme and could be worth looking into in the future. :)

Thanks for letting me rubberduck debug this over here. Hope it helps some else! :D

**Comment by evilebottnawi** [comment]
@japalo great! If you have the time to do PR (add this caveat to readme), I will be happy, thanks!

**Comment by machty** [comment]
@japalo Thanks for sharing your notes; was running into issues of lossiness for a particular icon that went away when I resized to 512x512 (and added the `--normalize` flag)

**Comment by lwojciechowski** [comment]
I found out that the problem was related to the low `units-per-em` in svg's `font-face` definition. I solved it putting there *empty* svg that had size of 600px x 600px and the `font-face` adjusted `units-per-em` to the biggest svg image it found. It works fine like this :)

**Comment by noiff** [comment]
It's not a webfont bug, it's a problem with svgicons2svgfont package. And solution is quite simple. You don't need to export big svg images from Illustrator, or add empty svg images with big size, just set propper options in config - `fontHeight: 600` and `normalize: true`.

**Comment by jimmyandrade** [comment]
> When adding complex icons some SVG optimization messes up the icons.

@japalo were you able to solve the problem after the suggestion of @noiff?
If so, I would like to close this issue. Otherwise, feel free to respond and I will try to help you.

**Comment by japalo** [comment]
@jimmyandrade oh, this was a long time ago i actually can't remember. That must have been the solution since i didn't comment anything further.

I will close this issue, and thank @noiff for the solution I must have missed to do two years back.

**Comment by jimmyandrade** [comment]
@japalo no prob 😄 Feel free to reopen the issue, in case you encounter this problem again.

And sorry for the delay in answering, we are resuming activities in this repository now, as we have more people contributing.
